export const ComplaintByPlant = [
  {
    id: 1,
    name: 'Tangerang',
    complainPoint: 40,
    color: '#6771DC',
    bgColor: 'bg-[#6771DC]',
  },
  {
    id: 2,
    name: 'Tirta Prima Indonesia',
    complainPoint: 20,
    color: '#6794DC',
    bgColor: 'bg-[#6794DC]',
  },
  {
    id: 3,
    name: 'Sanpan Agung',
    complainPoint: 40,
    color: '#C767DC',
    bgColor: 'bg-[#C767DC]',
  },
]

export const ComplaintByConclusion = [
  {
    id: 1,
    name: 'Conclusion no judge',
    complainPoint: 40,
    color: '#6771DC',
    bgColor: 'bg-[#6771DC]',
  },
  {
    id: 2,
    name: 'Not Justified',
    complainPoint: 30,
    color: '#DC67AC',
    bgColor: 'bg-[#DC67AC]',
  },
  {
    id: 3,
    name: 'Justified',
    complainPoint: 20,
    color: '#DCD267',
    bgColor: 'bg-[#DCD267]',
  },
  {
    id: 4,
    name: 'Not to be judge',
    complainPoint: 10,
    color: '#67DC97',
    bgColor: 'bg-[#67DC97]',
  },
]

export const ComplaintByProduct = [
  {
    id: 1,
    name: 'Bintang 0.0%',
    complainPoint: 90,
    color: '#6794DC',
  },
  {
    id: 2,
    name: 'Bintang Crystal',
    complainPoint: 40,
    color: '#6794DC',
  },
  {
    id: 3,
    name: 'Bintang Pilsener',
    complainPoint: 110,
    color: '#6794DC',
  },
  {
    id: 4,
    name: 'Bintang Raddler',
    complainPoint: 45,
    color: '#6794DC',
  },
  {
    id: 5,
    name: 'Green Sands',
    complainPoint: 90,
    color: '#6794DC',
  },
  {
    id: 6,
    name: 'Heineken',
    complainPoint: 90,
    color: '#6794DC',
  },
]

export const CompaintByStatusAndInvestigator = [
  {
    id: 1,
    name: 'Nadia Ishma',
    complainName: 'Ticket Open',
    complainName2: 'Ticket Closed',
    complainPoint: 40,
    complainPoint2: 100,
    color: '#DC67AC',
    color2: '#6771DC',
    bgColor: 'bg-[#DC67AC]',
    bgColor2: 'bg-[#6771DC]',
  },
  {
    id: 2,
    name: 'Agung Hadi Kusuma',
    complainName: 'Ticket Open',
    complainName2: 'Ticket Closed',
    complainPoint: 10,
    complainPoint2: 90,
    color: '#DC67AC',
    color2: '#6771DC',
  },
  {
    id: 3,
    name: 'Shapira Bella',
    complainName: 'Ticket Open',
    complainName2: 'Ticket Closed',
    complainPoint: 50,
    complainPoint2: 200,
    color: '#DC67AC',
    color2: '#6771DC',
  },
]

export const ComplaintHistory = [
  {
    id: 1,
    issueInvestigator: 'Nadia Ishma',
    category: 'Product',
    subCategory: 'TBC',
    brand: 'Bintang',
    packagingType: 'Can Jumbo',
    source: 'Distributor',
    averageDays: '30:26:30',
    Conclusion: 'Conclution no judge',
  },
  {
    id: 2,
    issueInvestigator: 'Agung Hadi Kusuma',
    category: 'Product',
    subCategory: 'TBC',
    brand: 'Bintang',
    packagingType: 'Can Jumbo',
    source: 'Distributor',
    averageDays: '00:42:43',
    Conclusion: 'Not Justified',
  },
  {
    id: 3,
    issueInvestigator: 'Shapira Bella',
    category: 'Product',
    subCategory: 'TBC',
    brand: 'Bintang Zero',
    packagingType: 'Can Jumbo',
    source: 'Distributor',
    averageDays: '19:05:19	',
    Conclusion: 'Justified',
  },
  {
    id: 4,
    issueInvestigator: 'Agung Hadi Kusuma',
    category: 'Product',
    subCategory: 'TBC',
    brand: 'Guinnes',
    packagingType: 'Bottle Jumbo',
    source: 'Outlet',
    averageDays: '09:50:35',
    Conclusion: 'Justified',
  },
  {
    id: 5,
    issueInvestigator: 'Agung Hadi Kusuma',
    category: 'Service',
    subCategory: 'TBC',
    brand: 'Bintang',
    packagingType: 'Bottle Small',
    source: 'Transporter',
    averageDays: '01:29:54',
    Conclusion: 'Not to be judge',
  },
  {
    id: 6,
    issueInvestigator: 'Agung Hadi Kusuma',
    category: 'Service',
    subCategory: 'TBC',
    brand: 'Radller',
    packagingType: 'Can Small',
    source: 'Outlet',
    averageDays: '11:11:36',
    Conclusion: 'Conclution no judge',
  },
  {
    id: 7,
    issueInvestigator: 'Nadia Ishma',
    category: 'Packaging',
    subCategory: 'TBC',
    brand: 'Bintang',
    packagingType: 'Can Jumbo',
    source: 'Distributor',
    averageDays: '19:05:19',
    Conclusion: 'Conclution no judge',
  },
]
