import Head from 'next/head'
import Image from 'next/image'
import { BsBarChartFill, BsFillArrowDownCircleFill } from 'react-icons/bs'
import BarCharts from '../components/BarCharts'
import ButtonTable from '../components/ButtonTable'
import DoughnutChart from '../components/DoughnutChart'
import Header from '../components/Header'
import Selector from '../components/Selector'
import SideMenu from '../components/SideMenu'
import StackCharts from '../components/StackCharts'
import TabelHistory from '../components/TabelHistory'
import {
  CompaintByStatusAndInvestigator,
  ComplaintByConclusion,
  ComplaintByPlant,
  ComplaintByProduct,
} from './Data'

export default function Home() {
  const doungnut1 = {
    labels: ComplaintByPlant.map((e) => e.name),
    datasets: [
      {
        data: ComplaintByPlant.map((e) => e.complainPoint),
        backgroundColor: ComplaintByPlant.map((e) => e.color),
      },
    ],
  }
  const doungnut2 = {
    labels: ComplaintByConclusion.map((e) => e.name),
    datasets: [
      {
        data: ComplaintByConclusion.map((e) => e.complainPoint),
        backgroundColor: ComplaintByConclusion.map((e) => e.color),
      },
    ],
  }
  const barData = {
    labels: ComplaintByProduct.map((e) => e.name),
    datasets: [
      {
        data: ComplaintByProduct.map((e) => e.complainPoint),
        backgroundColor: ComplaintByProduct.map((e) => e.color),
        barThickness: 72,
      },
    ],
  }
  const stackData = {
    labels: CompaintByStatusAndInvestigator.map((e) => e.name),
    datasets: [
      {
        label: 'Ticket Open',
        data: CompaintByStatusAndInvestigator.map((e) => e.complainPoint),
        backgroundColor: CompaintByStatusAndInvestigator.map((e) => e.color),
        barThickness: 92,
      },
      {
        label: 'Ticket Closed',
        data: CompaintByStatusAndInvestigator.map((e) => e.complainPoint2),
        backgroundColor: CompaintByStatusAndInvestigator.map((e) => e.color2),
        barThickness: 92,
      },
    ],
  }
  return (
    <div className='bg-slate-100'>
      <Head>
        <title>Complaint Report</title>
        <meta name='description' content='Generated by Complaint Report' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <div className='grid grid-cols-11'>
        <SideMenu />
        <div className='col-span-9 bg-blue-150 p-[20px] bg-blue-50'>
          <div className='w-full h-full bg-white flex flex-col gap-3'>
            <div className='w-full rounded-lg bg-white h-[57px] flex justify-start items-center px-[25px] shadow-sm gap-3'>
              <BsBarChartFill size={20} color='#445AD2' />
              <span>Complaint Report</span>
            </div>
            <div className='w-full px-[24px] py-[38px] bg-white min-h-[50px]'>
              <div className='flex flex-row justify-between items-center'>
                <span className='font-bold text-lg'>Complaint Report</span>
                <button className='h-[32px] w-[170px] bg-[#445AD2] rounded-md flex flex-row justify-between items-center px-[16px] text-white active:bg-white active:text-[#445AD2] active:border-2 active:border-slate-300'>
                  <BsFillArrowDownCircleFill size={18} />
                  <span className='text-sm font-bold'>Download Report</span>
                </button>
              </div>
            </div>

            {/* doungnut chart */}
            <div className='w-full flex justify-between px-[24px]'>
              <DoughnutChart
                dataSet={doungnut1}
                label='Complaint by Plant'
                dataLabel={ComplaintByPlant}
              />
              <DoughnutChart
                dataSet={doungnut2}
                label='Complaint by Conclusion'
                dataLabel={ComplaintByConclusion}
              />
            </div>

            {/* bar Chart */}
            <div className='px-[24px]'>
              <BarCharts dataSet={barData} label='Complaint by Product' />
            </div>

            {/* stack chart */}
            <div className='px-[24px]'>
              <StackCharts
                dataSet={stackData}
                label='Compaint by Status and Investigator'
                dataLabel={CompaintByStatusAndInvestigator[0]}
              />
            </div>

            {/* table */}
            <div className='px-[24px]'>
              <TabelHistory label='Complaint History' />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
